stt:
  model_size: "medium.en"
  language: "en"
  device: "cpu"
  compute_type: "int8"

tts:
  model_path: "./tts/voice_models/en_US-lessac-medium.onnx"
  config_path: "./tts/voice_models/en_US-lessac-medium.onnx.json"
  default_speaker: 0

server:
  host: "0.0.0.0"
  port: 5001
  debug: true
